import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>The Next Stack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <h1 className="text-3xl font-bold underline">Add New Word</h1>
        <form action="">
          <input type="text" name="word" id="word" />
          <input type="text" name="meanig" id="meanig" />
          <button>Save</button>
        </form>
      </main>
    </>
  );
}
